# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: Build with Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.8'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: false
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      goals: 'package'

- job: macOS
  pool:
    vmImage: 'macOS-10.14'
  steps:
  - task: Build with Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.8'
      jdkArchitectureOption: 'x64'
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      goals: 'package'
      publishJUnitResults: true 
      mavenVersionOption: 'Default' # Options: default, path
      checkStyleRunAnalysis: true # Optional

- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - task: Build with Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.8'
      jdkArchitectureOption: 'x64'
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      goals: 'package'
      publishJUnitResults: true 
      mavenVersionOption: 'Default' # Options: default, path
      checkStyleRunAnalysis: true # Optional
